version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: flavorconnect-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flavorconnect
      MYSQL_USER: flavorconnect
      MYSQL_PASSWORD: flavorconnect
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flavorconnect-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: flavorconnect-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - flavorconnect-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flavorconnect-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - MYSQL_USER=flavorconnect
      - MYSQL_PASSWORD=flavorconnect
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=flavorconnect
      - MYSQL_URL=mysql+pymysql://flavorconnect:flavorconnect@mysql:3306/flavorconnect
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=flavorconnect_chat
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    networks:
      - flavorconnect-network

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flavorconnect-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - flavorconnect-network

  # Sync Scheduler
  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile.scheduler
    container_name: flavorconnect-scheduler
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - MYSQL_USER=flavorconnect
      - MYSQL_PASSWORD=flavorconnect
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=flavorconnect
      - MYSQL_URL=mysql+pymysql://flavorconnect:flavorconnect@mysql:3306/flavorconnect
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=flavorconnect_chat
    networks:
      - flavorconnect-network

networks:
  flavorconnect-network:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: 